### ISSUE TITLE
Debugger Support

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/blueprint#11]
RIght now there's no debugging other than `console.log` statements, and that's a pain for larger applications. Duktape does have builtin debug support, just need to find a way to integrate that with this project (https://github.com/svaarala/duktape/blob/master/doc/debugger.rst). I'd like to have an interface something like React Native where you hit CMD+D and it automatically pops up the debugger in a browser window.

**Comment by JoshMarler** [comment]
@nick-thompson, So I'm starting on this now. This issue is probably the best place to discuss initial approach.

Initial ideas:

I think it would be nice to follow the approach used for hot reloading in ReactApplicationRoot. If JUCE_DEBUG is enabled then we add ReactApplicationRoot as a juce::KeyListener to itself and in response to CMD-D/CTRL-D we call duk_debugger_attach(), CMD-C/CTRL-C or similar for detach. We will need to include/compile the tcp protocol implementation in the examples (duk_trans_socket_unix.c). 

One thing to consider is how to enable the necessary compiler defs for duktape debug support. We need to enable ```DUK_USE_DEBUGGER_SUPPORT``` and ```DUK_USE_INTERRUPT_COUNTER``` as a minimum. The recommended way to enable such options is using duktape's configure.py script. At the moment blueprint.h/blueprint.cpp just include the stock src-noline/duktape.h/.c files. It would be good to provide users of Blueprint with a mechanism to use their own custom configured headers. 

I will start hacking on this now but would be interested to hear your thoughts. I'm going to have a play with the VSCode extension as a test approach: https://marketplace.visualstudio.com/items?itemName=HaroldBrenes.duk-debug

**Comment by nick-thompson** [comment]
Cool, I'll be so excited to see this!

Definitely like the CMD-D/CTRL-D idea in DEBUG.

The compile definitions I'm currently doing here: https://github.com/nick-thompson/blueprint/blob/master/blueprint/blueprint.cpp#L31 I know that it's not the _right_ way to embed duktape and makes custom configuration definitely difficult. I think we could get away with this setup for those two defs, but maybe afterward we should consider a new, better way to integrate duktape?

**Comment by JoshMarler** [comment]
Ha yeah I'm just hacking that in now to get started. Yeah fair enough, it's not an essential thing right now. I've been pleasantly surprised with the performance on linux just using the stock configuration so far anyways.

**Comment by JoshMarler** [comment]
@nick-thompson, So I can get the debugger attached using both the vscode duktape extension and the web based debugger in duktape. However I'm struggling to get breakpoints working. I believe this is an issue with having an single minified bundle and duktape not supporting source maps. 

Duktape has an open issue to add source map support. The vscode extension supposedly supports source maps however I'm hitting issues with it. The logging shows the following:

```
[unmapSourceFile] Unmapping file: /home/josh/development/Mixer/Software/Source/ui/jsui/common/components/src/ToggleButton.js
[getSourceNameByPath] Path found in source root '/home/josh/development/Mixer/Software/Source/ui/jsui' source name: common/components/src/ToggleButton.js
[unmapSourceFile] Path under root: common/components/src
[scanDir] Error reading directory: /home/josh/development/Mixer/Software/Build/jsui/common/components/src
Unknown source file: /home/josh/development/Mixer/Software/Source/ui/jsui/common/components/src/ToggleButton.js
```
Suggests it's looking for jsui/common/components/src at the output/build location and expecting a ToggleButton.js file at that location. 

Any thoughts on this? I'm probably going to hit the limits of my webpack/bundling skills here but will persist.

**Comment by JoshMarler** [comment]
Initial work started in https://github.com/nick-thompson/blueprint/pull/61

**Comment by nick-thompson** [comment]
Boom!! I'll take a quick pass on the PR now. I agree that the chrome dev tools transport could be a lot, definitely happy to defer that. Being able to do _any_ debugging will be amazing

**Comment by JoshMarler** [comment]
Awesome. Think I've found fix for the GETHEAPOBJINFO failure too so this might be fully functioning shortly. Requires a webpack change to function reliably etc. so some more bits to push up shortly.

**Comment by nick-thompson** [comment]
Ah interesting. What's the webpack change?

**Comment by JoshMarler** [comment]
Basically just ensuring source map entries are absolute:

devtoolModuleFilenameTemplate: 'webpack:///[absolute-resource-path]'

**Comment by nick-thompson** [comment]
Ok cool, didn't know about those options!

**Comment by JoshMarler** [comment]
Will move all conversation on this over to the PR now but heap object inspection is now working so you can interrogate both "this" and local vars inside component member functions

**Comment by JoshMarler** [comment]
> Ok cool, didn't know about those options!

Ha me neither. There has been much pain debugging the extension to workout why my source map wasn't working for all files. I've burnt out my Google searching quota for the day.

**Comment by JoshMarler** [comment]
@nick-thompson wonder if this can be closed now ? VsCode debug is documented and fairly stable.

**Comment by nick-thompson** [comment]
Yup totally. If anything, this issue is now basically tracking a duplicate of #63. Thanks
