### ISSUE TITLE
Add GitHub Action to build PRs (and commits to master?) for Linux/macOS/Windows

### ISSUE THREAD

**Issue by jrlanglois** [nick-thompson/blueprint#181]
It would be nice to have this automated to an extent or other.

Relies on #171 .

**Comment by nick-thompson** [comment]
100%, this is becoming a priority. Thanks for opening

**Comment by nick-thompson** [comment]
See #193 

We now compile for all major platforms and run our node build on ubuntu. Then see #136. I think the next step is to CMake-ify our TestRunner, add it to the top-level CMakeLists so that we build that and the gainPlugin on every commit, then run the gainplugin jsui build as the final piece of our CI workflow.

I'm going to leave #136 open to track that effort, and go ahead and close this one.
