### ISSUE TITLE
Add some more core components. 

### ISSUE THREAD

**Issue by JoshMarler** [nick-thompson/blueprint#70]
@nick-thompson, 

I find myself at the point where I'll soon need to build the below core components. Are these something that should be a part of Blueprint/Blueprint-Extras?  A modal/dialog component feels like it may well belong in the core Blueprint library. 

**Modal/Dialog**
https://reactnative.dev/docs/modal
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
https://docs.juce.com/master/classPopupMenu.html

**TextInput**
Already covered here: https://github.com/nick-thompson/blueprint/issues/21

**Picker/ComboBox**
https://reactnative.dev/docs/picker
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
https://docs.juce.com/master/classComboBox.html

I'd love to know what you think about these controls and where their place is? It feels like Modal/Dialog and TextInput should definitely be part of the core library. What about ComboBox ? 

Should we add separate issues for a modal and a picker?

**Comment by JoshMarler** [comment]
@nick-thompson I'd be more than happy to tackle some of this by the way! My main interest is which of these things should or should not be part of Blueprint "core".

**Comment by nick-thompson** [comment]
Totally, great idea. TextInput should definitely be core, as it requires a custom native view. Both Modal and Picker could be built by compositions of View/Image/Text and so would require no custom native. This boundary (whether or not an implementation of a new view would require custom native code) has been more or less where I want to draw the line between core and non-core components (as well as those components that need custom native but are very specifically tied to existing JUCE components), at least initially. That way as we approach beta/release our API surface area remains comparatively smaller, which I think is a helpful design constraint and a helpful strategy to mitigate maintaining legacy decisions as we move on from beta/release to the next release.

That said, I would _love_ to see community js libraries popping up for things like a modal component or a picker component, and would be very happy to help promote that in the core blueprint documentation. I could even imagine like a Bootstrap-inspired library of useful Blueprint components (Button, Modal, Picker, Knob, Slider...) with neatly designed default styles. I feel like something like that could be super popular 

Curious to hear what you think of that idea? And if you're interested in it, I would be psyched to see you lead the first community-built component library for blueprint! 😃

**Comment by nick-thompson** [comment]
After sleeping on this a bit, I think I'm actually more in agreement with your intuition @JoshMarler than I am with what I said above.

I do think it's worth maintaining clarity around this boundary of what components need custom native code and what components don't. In a sense, I think those components that strictly need custom native are the core building blocks, and ideally we can define the minimal set of core building blocks that enable building any other component by some composition of the core blocks. If we succeed in that, then we've nailed the composition and nailed our core blocks.

That said, I'm feeling more in line with your intuition that components like Modal and Picker should be in the core library– and less in line with my original idea that this "needs custom native" boundary is the right boundary for our component library. I think part of React-Native's success was that the provided component library enabled people to build apps super quickly. I think we should be very thoughtful about what we do add to the component library (because adding a bunch of esoteric components becomes a maintenance burden), but should aim to support a set that covers a wide set of use cases easily.

I'm reading along here https://reactnative.dev/docs/components-and-apis in the React Native docs and I think it'd be a good idea for us to define our library similarly. I'll take a stab below, let me know what you think.

**Basic Components** (Requiring custom native)
* View
* Image
* Text
* TextInput
* ScrollView
* Canvas

**UI Components** (Composed of Basic Components)
* Button
* Modal
* AnimatedView (#31 – maybe a Basic Component, also maybe a way to do this with just View and some AnimatedValue class like ReactNative does it)
* Picker (I think I could be convinced either way– keep this in our core library or not?)

I could also see adding a `Slider` and a `Knob` to the UI Components list since we're dealing mostly with audio apps. Then of course there's the `blueprint_extras` module (#53) for tight integrations with existing JUCE components. What do you think?

**Comment by JoshMarler** [comment]
Hey @nick-thompson!

Sorry, been quiet on the Blueprint front for a couple days. 

So, I totally agree that the more complex components should be build up from the "core" views/components, that does indeed sound like a great battle test of the core APIs. 

I do think there is some value in having some generic UI components that people are likely to require in `blueprint_core` but I suppose that depends on how tightly integrated the `blueprint_extra` module becomes. I guess it's a decision on how "core"/"bare-bones" the `core` module should be.

Off the top of my head the components I expect people will want are as you've suggested along with maybe `ToggleButton` (suspect there are a few others like a `ListView` or something). 

I've been writing generic components for things like `Slider` and `Button` which basically use a `Canvas` element internally and then provide a user overridable `onDraw(ctx)` prop (similar to the juce LookAndFeel approach). They can have a default prop with some generic `onDraw` implementation. These components then hold no state and offer your typical `onValueChanged` or `onToggleChanged` prop callbacks for users. I wonder if this would be a good pattern to follow in the core blueprint library? I'd be happy to submit some components for you to review. 

I've then got higher level components which wrap these generic components, thing along the lines of `ParamSlider` and `ParamButton` which basically use `ParameterValueStore` and/or `EventBridge` internally. These wrapper components pass `onValueChange` callback props down to the basic components `Slider`/`Button` with implementations that dispatch an update to C++ application code via `ParameterValueStore` or `EventBridge` etc.

I mention this as if we decide the core/generic components will live in the `core` module maybe `blueprint_extra` should be the home for higher level components like `ParamSlider`. You could also offer more esoteric components like `WaveformDisplay`, `FrequencyResponsePlot` etc. etc. 

Would be cool to decide on the distinction here and start building some stuff!

**Comment by JoshMarler** [comment]
@nick-thompson, I have a related question which might make sense to add here. 

So I'm currently working on out data-models for our React/Blueprint based components. We have data model properties/objects which use interfaces very similar to `juce::AudioProcessorParameter`.

As such I've been writing things like `ParamSlider` as discussed which wrap a basic `Slider` component an augment it by having the `Slider` component's `onValueChanged` callback trigger a parameter update. Such a class feels like a worth addition to the extras module so I've deliberately kept this in mind and ensured our apps data models can be used with `ParamSlider` and the like as well as allowing `ParamSlider` to be used with `juce::AudioProcessorParameter`. 

Functions called from `ParamSlider` are as you would expect:

`beingParameterChangeGesture`
`endParameterChangeGesture`
`setParameterValue`

Now there are cases where we might want to fetch a parameters range, name, text value etc. i.e. bind calls through to:

`juce::AudioProcessorValueTreeState::getParameterRange(StringRef paramID)`
`juce::AudioProcessorParameter::getName()`
`juce::AudioProcessorParameter::getCurrentValueAsText()`

What do you think would be a better pattern for such a component, to call registered native functions like `getParameterName(StringRef paramID)` or to provide a `getParameter(id)` function which returns a JS AudioProcessorParameter object (bound to a juce::DynamicObjectInstance) and then call `param.getCurrentValueAsText` directly in JS ? 

Sorry this might be hijacking this thread somewhat ... we can start a discussion elsewhere for this. Might be time to start thinking about getting the extras module/repo together to such questions can be asked there.

**Comment by nick-thompson** [comment]
> I do think there is some value in having some generic UI components that people are likely to require in `blueprint_core` but I suppose that depends on how tightly integrated the `blueprint_extra` module becomes. I guess it's a decision on how "core"/"bare-bones" the `core` module should be.

Yea after my latest post, I totally agree. The list I put together up there I think can all be included in blueprint core, with only the "basic components" requiring any custom native part. `blueprint_extras`, as I see it, would be the home for any js or native components that are tightly tied to JUCE internals, and I'll elaborate on that below

> Off the top of my head the components I expect people will want are as you've suggested along with maybe `ToggleButton` (suspect there are a few others like a `ListView` or something).

Yea `ListView` is probably a good one, and a tricky one to build (I'll open some issues for each of these components once we nail down our list, and elaborate on each therein). `ToggleButton` I've thought about– it seems like a simple wrapper on a `Button` so I'm tempted to just let people roll it themselves. Especially when people's ideas of what a toggled state looks like (is it a checked box? is it a filled circle?) and what a non-toggled state looks like varies so drastically.

```
const styles = this.state.toggled ? toggleStyles : defaultStyles;
return (<Button {...styles} onClick={this.handleToggle} />);
```

> I've been writing generic components for things like `Slider` and `Button` which basically use a `Canvas` element internally and then provide a user overridable `onDraw(ctx)` prop (similar to the juce LookAndFeel approach). They can have a default prop with some generic `onDraw` implementation. These components then hold no state and offer your typical `onValueChanged` or `onToggleChanged` prop callbacks for users. I wonder if this would be a good pattern to follow in the core blueprint library? I'd be happy to submit some components for you to review.

👍 100%! In my opinion that's exactly the right way to write these types of components. I'd be happy to review them. Out of curiousity– why the `Canvas` for a `Button`? Could the drawing be satisified with the `View` props of background-color, border-radius, etc?

> I've then got higher level components which wrap these generic components, thing along the lines of `ParamSlider` and `ParamButton` which basically use `ParameterValueStore` and/or `EventBridge` internally. These wrapper components pass `onValueChange` callback props down to the basic components `Slider`/`Button` with implementations that dispatch an update to C++ application code via `ParameterValueStore` or `EventBridge` etc.
> 
> I mention this as if we decide the core/generic components will live in the `core` module maybe `blueprint_extra` should be the home for higher level components like `ParamSlider`. You could also offer more esoteric components like `WaveformDisplay`, `FrequencyResponsePlot` etc. etc.

Yea, this is excellent. Resuming my first comment above about the distinction between blueprint_core and blueprint_extras, it sounds here like we're on the same page. I envision these going in blueprint_extras because they're conceptually coupled with JUCE's idea of a Parameter and a parameter change (`beginParameterChange`, `endParameterChange`, etc), or for example if we were to write that native component which wrapped a `juce::Slider` directly. And yea I think WaveformDisplay and FrequencyResponsePlot would be awesome and probably make sense for `blueprint_extras` too, at least initially

**Comment by JoshMarler** [comment]
<ToggleButton I've thought about– it seems like a simple wrapper on a Button so I'm tempted to just let people roll it themselves. Especially when people's ideas of what a toggled state looks like (is it a checked box? is it a filled circle?) and what a non-toggled state looks like varies so drastically.

I'd say that's fair enough, I wasn't thinking so much that we would dictate the painting of a toggle button. Just provide a wrapper around `Button` which dealt with `toggled` state and expose the same `drawButton` property callback. Either way really. 

<Out of curiousity– why the Canvas for a Button? Could the drawing be satisified with the View props of background-color, border-radius, etc?

It totally could yeah, I've seen the Button in the example apps. Mainly I felt Canvas was a consistent approach as all core components would just provide a `drawThing` property callback which gets a canvas object, maybe you want a button shapped like a star?

Cool, totally agree on the likes of `ParamSlider` being part of the extras module. Maybe we should start a concrete list on this issue to refer to and then go and open an issue/ticket for each component. 

We could do the same on the "extras" project once we get that up and running. Open issues/feature-requests for components. The `Param` based components will probably make a good starting point and maybe provide a nice test-bed for the extras module concept.

**Comment by JoshMarler** [comment]
@nick-thompson, with all this in mind, should we start an issue for "Start/Create the extras module" ? Would be good to track that and maybe detail who you think it should interoperate with Blueprint core. i.e. is one thing a submodule of the other, how should examples using core v.s. extras components be presented in the docs etc. etc.

**Comment by nick-thompson** [comment]
> What do you think would be a better pattern for such a component, to call registered native functions like `getParameterName(StringRef paramID)` or to provide a `getParameter(id)` function which returns a JS AudioProcessorParameter object (bound to a juce::DynamicObjectInstance) and then call `param.getCurrentValueAsText` directly in JS ?
> 
> The alternative is to just always push this information through to JS via events but I feel like that doesn't fit things like `getRange` all that well (thought ranges in my case might change, they don't on AudioProcessorParameter). We don't want to have to keep the ranges in sync between C++ and JS so there should be some mechanism for such things.

Hmm right, this gets into the territory about data flow / state management and trying not to be too prescriptive. In the GainPlugin example, I dispatch the kind of state you're talking about (param names and ranges) as an event from native into js-land and hang onto it in the ParameterValueStore, but I see the appeal for being able to just call native methods. Maybe part of `blueprint_extras` is a set of installed native methods? For example...

```cpp
// On the cpp side
blueprint::extras::registerParameterMethods(myEcmaEngine, myAudioParameterValueTreeState);
```

```js
// On the js side
const extras = require('blueprint-extras');

extras.beginParameterChangeGesture(paramId);
extras.setValueNotifyingHost(paramId, 0.5);
extras.endParameterChangeGesture(paramId);
const [default, min, max] = extras.getParameterRange(paramId);
const name = extras.getParameterName(paramId);
```

What do you think about that idea? That's definitely not an exhaustive list of what that API would look like, just totally off the top of my head

**Comment by nick-thompson** [comment]
@JoshMarler yea, definitely. I'll go ahead and start some new issues now. If I have time too I'll try to start organizing labels and such so that we can track getting to a beta release

**Comment by JoshMarler** [comment]
> > What do you think would be a better pattern for such a component, to call registered native functions like `getParameterName(StringRef paramID)` or to provide a `getParameter(id)` function which returns a JS AudioProcessorParameter object (bound to a juce::DynamicObjectInstance) and then call `param.getCurrentValueAsText` directly in JS ?
> > The alternative is to just always push this information through to JS via events but I feel like that doesn't fit things like `getRange` all that well (thought ranges in my case might change, they don't on AudioProcessorParameter). We don't want to have to keep the ranges in sync between C++ and JS so there should be some mechanism for such things.
> 
> Hmm right, this gets into the territory about data flow / state management and trying not to be too prescriptive. In the GainPlugin example, I dispatch the kind of state you're talking about (param names and ranges) as an event from native into js-land and hang onto it in the ParameterValueStore, but I see the appeal for being able to just call native methods. Maybe part of `blueprint_extras` is a set of installed native methods? For example...
> 
> ```c++
> // On the cpp side
> blueprint::extras::registerParameterMethods(myEcmaEngine, myAudioParameterValueTreeState);
> ```
> 
> ```js
> // On the js side
> const extras = require('blueprint-extras');
> 
> extras.beginParameterChangeGesture(paramId);
> extras.setValueNotifyingHost(paramId, 0.5);
> extras.endParameterChangeGesture(paramId);
> const [default, min, max] = extras.getParameterRange(paramId);
> const name = extras.getParameterName(paramId);
> ```
> 
> What do you think about that idea? That's definitely not an exhaustive list of what that API would look like, just totally off the top of my head

This is literally the exact design I had in mind heh. A generic object/function to register those native methods regardless of the component type hosting the `ReactApplicationRoot` instance. Totally agree.

**Comment by nick-thompson** [comment]
Ok see #53 for tracking the part of the discussion here that relates to `blueprint_extras`.

Re-focusing this issue here to track those components which will be part of blueprint core. I'll paste the same list from above with some quick additions:

**Basic Components** (Requiring custom native)
* View (Done?)
* Image (#14)
* Text  (#6)
* TextInput (#21)
* ScrollView (Done?)
* Canvas (#48)
* AnimatedView (#31) (Perhaps we can do this via just a `View` and some AnimatedValue class, which would mean this wouldn't necessarily be a component in our library)

**UI Components** (Composed of Basic Components)
* Button
* Modal
* ListView
* Slider
* Knob
* Picker (I think I could be convinced either way– keep this in our core library or not?)

@JoshMarler what do you think? If I get your +1 on this list, I'll go ahead and write out discrete issues for each of the remaining components. Also, think all of this is part of the beta milestone? (I would say yes I think)

**Comment by JoshMarler** [comment]
@nick-thompson, I think I agree with the list. 

Couple points:

What is the distinction between `Slider` and `Knob` here ? 

Personally I'd say if `Slider` is in core `Picker` / `ComboBox` feels perfectly valid, it's a thing I'd reach for often. 

>  Also, think all of this is part of the beta milestone

Yeah seems totally reasonable to me, you want people to be able to get up and going with `blueprint` / `react-xpaudio` with ease I would say. That's likely to provide a good first experience with the framework and help cement it's popularity. Otherwise you'll have newbies asking "Why on earth can't I just declare a button?"

**Comment by nick-thompson** [comment]
> Yeah seems totally reasonable to me, you want people to be able to get up and going with `blueprint` / `react-xpaudio` with ease I would say. That's likely to provide a good first experience with the framework and help cement it's popularity. Otherwise you'll have newbies asking "Why on earth can't I just declare a button?"

:+1:



> What is the distinction between `Slider` and `Knob` here ?

Good point– if you can just supply your own `onDraw` to `Slider` to overwrite the default `onDraw`, then there really is no difference. Let's drop the `Knob` from that list. We'll provide a `Slider` and if users want to draw that as a knob they can just provide an `onDraw` for that, and if they want linear/horizontal slider customizations, same thing.

> Personally I'd say if `Slider` is in core `Picker` / `ComboBox` feels perfectly valid, it's a thing I'd reach for often.

Ok cool, let's go for it.

I'll update the list above and start writing out some individual issues

**Comment by JoshMarler** [comment]
> Good point– if you can just supply your own onDraw to Slider to overwrite the default onDraw, then there really is no difference. Let's drop the Knob from that list. We'll provide a Slider and if users want to draw that as a knob they can just provide an onDraw for that, and if they want linear/horizontal slider customizations, same thing.

Yeah totally, for instance I've given my `Slider` base component a `sliderStyle` prop which is basically an enum on linear, linear-horizontal and rotary. That prop is passed through to the user supplied `drawSlider`/`onDraw` callback. 

Quick in-progress example (I need to give these components more love, concentrating on data-model binding at the moment):

```
class Slider extends Component {
  constructor(props) {
    super(props);

    this._onMeasure = this._onMeasure.bind(this);
    this._onMouseDown = this._onMouseDown.bind(this);
    this._onMouseDrag = this._onMouseDrag.bind(this);

    this._drawSlider = this._drawSlider.bind(this);

    // During a drag, we hold the value at which the drag started here to
    // ensure smooth behavior while the component state is being updated.
    this._valueAtDragStart = 0.0;

    this.state = {
      width: 0,
      height: 0,
    };
  }

  _onMeasure(width, height) {
    this.setState({
      width: width,
      height: height,
    });
  }

  _onMouseDown(mouseX, mouseY) {
    this._valueAtDragStart = this.props.value;
  }

  _onMouseDrag(mouseX, mouseY, mouseDownX, mouseDownY) {
    const dx        = mouseX - mouseDownX;
    const dy        = mouseDownY - mouseY;
    let sensitivity = (1.0 / 200.0);
    let value       = 0.0;

    switch (this.props.sliderStyle) {
      case Slider.SliderStyles.LINEAR_VERTICAL: {
          value = Math.max(0.0, Math.min(1.0, this._valueAtDragStart + dy * sensitivity));
      }
        break;
      case Slider.SliderStyles.LINEAR_HORIZONTAL: {
          value = Math.max(0.0, Math.min(1.0, this._valueAtDragStart + dx * sensitivity));
      }
        break;
      case Slider.SliderStyles.ROTARY: {
          value = Math.max(0.0, Math.min(1.0, this._valueAtDragStart + (dx + dy) * sensitivity));
      }
        break;
      default:
        break;
    }

    this.props.onValueChanged(value);
  }

  _drawSlider(ctx) {
    const {width, height} = this.state;
    this.props.drawSlider(ctx, width, height, this.props.value, this.props.sliderStyle);
  }

  render() {
    const {onValueChanged, value, sliderStyle, drawSlider, ...other} = this.props;
    return (
        <View
            {...other}
            onMeasure={this._onMeasure}
            onMouseDown={this._onMouseDown}
            onMouseDrag={this._onMouseDrag}>
          <Canvas autoclear={true} {...styles.canvas} onDraw={this._drawSlider} />
          {this.props.children}
        </View>
    );
  }
}

const styles = {
  canvas: {
    'width': '100%',
    'height': '100%',
    'interceptClickEvents': false
  }
};

Slider.SliderStyles = {
  LINEAR_VERTICAL:       "LinearVertical",
  LINEAR_HORIZONTAL: "LinearHorizontal",
  ROTARY:                         "Rotary"
};

export default Slider;
```

**Comment by JoshMarler** [comment]
@nick-thompson, I've got some useful components coming together now, Slider, RadioGroup, Button, ToggleButton etc. I've got a few questions around what you think might be an appropriate design pattern for these "basic" components. For example, with the exception of width,height I've found keeping these components "stateless" (i.e. their values are props and they emit a callback) works very well. 

Is this issue the correct place for us to discuss a generalised design-approach for these components? I can drop some example code over here if yes.

**Comment by nick-thompson** [comment]
Great! Yea, I think this is a good spot for the discussion as it's kind of a "design theme" across all these components.

+1 for stateless indeed, and I think width/height makes sense for drawing.

**Comment by JoshMarler** [comment]
Cool Cool. I'll tidy a bit of stuff up and drop a couple component examples on here and we can discuss.

**Comment by nick-thompson** [comment]
> For example, should the basic `Button` component just use the primitives `border-radius`, `border-path` etc. Then we provide a `DrawableButton` or similar which renders via Canvas for more complex UI options?

Ah, yea, I like that. I'd say we start there.

If I understand right, I think we could even skip the `SvgButton`, because it should be just a simple composition of existing components:

```
import infoIcon from './icons/info.svg';
import {
  Button,
  Image,
} from 'juce-blueprint';

function IconButton(props) {
  const {source, ...other} = props;

  return (
      <Button {...styles.button} {...props}> // Unpacks things like outer styles, onClick, etc
        <Image interceptClickEvents={false} {...styles.iconButton} source={source} /> // Directs `source` to the right place
      </Button>
  );
}

// Then later I can use it just like you'd expect
<IconButton {...styles.infoButton} source={infoIcon} onClick={this._onClick} />
```

Of course the spefics of what an icon inside of a button should look like are part of the design language, and in my experience it can be different project to project, so this kind of abstraction I think makes sense to leave up to the user.

That said, surely there are cases of more complex design decisions, and I think that makes a strong case for the `DrawableButton`

**Comment by JoshMarler** [comment]
@nick-thompson , I think we can close this as everything here is covered by individual component issues.
